---
- name: Find installed files matching the version pattern
  ansible.builtin.find:
    paths:
      - "{{ python_install_dir }}/bin"
      - "{{ python_install_dir }}/lib"
      - "{{ python_install_dir }}/lib/pkgconfig"
    patterns:
      - "idle{{ python_minor }}"
      - "libpython{{ python_minor }}*"
      - "pip{{ python_minor }}"
      - "pydoc{{ python_minor }}"
      - "python{{ python_minor }}*"
      - "python-{{ python_minor }}*"
  register: python_installed

- name: Delete matched Python versioned binaries
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ python_installed.files }}"
  become: true
  when: python_installed.matched > 0

- name: Find installed man pages matching the version pattern
  ansible.builtin.find:
    paths:
      - "{{ python_install_dir }}/share/man/man1"
    patterns:
      - "python{{ python_minor }}*"
  register: python_installed

- name: Delete matched Python versioned man pages
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ python_installed.files }}"
  become: true
  when: python_installed.matched > 0

- name: Delete installed Python versioned directories
  ansible.builtin.file:
    path: "{{ python_install_dir }}/{{ item }}/python{{ python_minor }}"
    state: absent
  become: true
  loop:
    - "lib"
    - "include"
...
