---
- name: Install dependencies (RedHat distros except EL 9 & 10)
  ansible.builtin.yum:
    name:
      - bzip2-devel
      - expat-devel
      - gcc
      - gcc-c++
      - gdbm-devel
      - libdb
      - libdb-devel
      - libffi-devel
      - libuuid-devel
      - make
      - ncurses
      - ncurses-devel
      - ncurses-libs
      - openssl-devel
      - readline-devel
      - sqlite-devel
      - tar
      - tcl-devel
      - tk-devel
      - xz
      - xz-devel
    state: present
  become: true
  retries: 3
  delay: 3
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] not in ('9', '10')

- name: Install dependencies (RedHat EL 9)
  ansible.builtin.yum:
    name:
      - bzip2-devel
      - expat-devel
      - gcc
      - gcc-c++
      - libdb
      - libdb-devel
      - libffi-devel
      - libuuid-devel
      - make
      - ncurses
      - ncurses-devel
      - ncurses-libs
      - openssl-devel
      - readline-devel
      - sqlite-devel
      - tar
      - tcl-devel
      - tk-devel
      - xz
      - xz-devel
    state: present
  become: true
  retries: 3
  delay: 3
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] == '9'

- name: Install dependencies (RedHat EL 10)
  ansible.builtin.yum:
    name:
      - bzip2-devel
      - expat-devel
      - gcc
      - gcc-c++
      - libffi-devel
      - libuuid-devel
      - make
      - ncurses
      - ncurses-devel
      - ncurses-libs
      - openssl-devel
      - readline-devel
      - sqlite-devel
      - tar
      - tcl-devel
      - tk-devel
      - xz
      - xz-devel
    state: present
  become: true
  retries: 3
  delay: 3
  when:
    - ansible_facts['os_family'] == "RedHat"
    - ansible_facts['distribution_major_version'] == '10'

- name: Install dependencies (Ubuntu)
  ansible.builtin.apt:
    name:
      - libbz2-dev
      - expat-devel
      - gcc
      - gcc-c++
      - libgdbm-dev
      - libdb-dev
      - libffi-dev
      - uuid-dev
      - make
      - libncurses-dev
      - libssl-dev
      - libreadline-dev
      - libsqlite3-dev
      - tar
      - tcl-dev
      - tk-dev
      - libxv-dev
      - liblzma-dev
    state: present
  become: true
  retries: 3
  delay: 3
  when: ansible_facts['distribution'] == "Ubuntu"
...
